# Generated by Django 6.0.4 on 2026-05-11 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "boundary_wkt",
                    models.TextField(
                        blank=True,
                        help_text="District boundary as WKT. Example: POLYGON((lon lat, ...)).",
                    ),
                ),
                ("centroid_latitude", models.FloatField(blank=True, null=True)),
                ("centroid_longitude", models.FloatField(blank=True, null=True)),
                (
                    "latest_capital_formation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rs crore",
                        max_digits=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["state", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="forecasts_d_name_bf804a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EconomicForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("predicted_yield", models.FloatField(help_text="In Metric Tons")),
                (
                    "nightlight_intensity",
                    models.FloatField(
                        default=0.0, help_text="Proxy for GDP/Economic Activity"
                    ),
                ),
                ("vegetation_index_avg", models.FloatField(default=0.0)),
                (
                    "capital_formation_proxy",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Rs crore", max_digits=20
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="forecasts.district",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date", "district__name"],
                "indexes": [
                    models.Index(
                        fields=["prediction_date"],
                        name="forecasts_e_predict_7b768e_idx",
                    ),
                    models.Index(
                        fields=["district", "prediction_date"],
                        name="forecasts_e_distric_6fc17b_idx",
                    ),
                ],
            },
        ),
    ]
