# Generated by Django 6.0.4 on 2026-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="boundary_geojson",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="district",
            name="boundary_source",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="economicforecast",
            name="data_source",
            field=models.CharField(
                default="User supplied observed inputs", max_length=200
            ),
        ),
    ]
