# Generated by Django 6.0.4 on 2026-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "forecasts",
            "0002_district_boundary_geojson_district_boundary_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="area_level",
            field=models.CharField(
                choices=[("district", "District"), ("state", "State")],
                default="district",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="economicforecast",
            name="area_level",
            field=models.CharField(
                choices=[("district", "District"), ("state", "State")],
                default="district",
                max_length=20,
            ),
        ),
    ]
